# Generated by Django 5.2.3 on 2026-02-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id_entrepot', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('code_entrepot', models.CharField(max_length=50, unique=True)),
                ('nom_entrepot', models.CharField(max_length=255)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'entrepots',
            },
        ),
        migrations.CreateModel(
            name='Emplacement',
            fields=[
                ('id_emplacement', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code_emplacement', models.CharField(max_length=50, unique=True)),
                ('zone', models.CharField(blank=True, max_length=50, null=True)),
                ('type_emplacement', models.CharField(max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('id_entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emplacements', to='warhouse.entrepot')),
            ],
            options={
                'db_table': 'emplacements',
            },
        ),
    ]
