# Generated by Django 5.2.3 on 2026-02-13 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0001_initial'),
        ('Users', '0006_utilisateur_is_banned'),
        ('warhouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emplacement',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='mise_a_jour_le',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='emplacement',
            name='statut',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('BLOCKED', 'Blocked')], default='AVAILABLE', max_length=50),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='adresse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='cree_le',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='id_emplacement',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='emplacement',
            name='type_emplacement',
            field=models.CharField(choices=[('STORAGE', 'Storage Location'), ('PICKING', 'Picking Location')], max_length=50),
        ),
        migrations.AlterField(
            model_name='entrepot',
            name='id_entrepot',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AnomalieDetection',
            fields=[
                ('id_anomalie', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_anomalie', models.CharField(choices=[('STOCK_NEGATIVE', 'Negative Stock Detected'), ('STOCK_EXCESSIF', 'Excessive Stock'), ('DISCREPANCY', 'Stock Discrepancy'), ('MOUVEMENT_SUSPECT', 'Suspicious Movement'), ('ACCES_NON_AUTORISE', 'Unauthorized Access')], max_length=50)),
                ('severite', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], max_length=50)),
                ('description', models.TextField()),
                ('id_entite_concernee', models.CharField(blank=True, max_length=100, null=True)),
                ('type_entite', models.CharField(blank=True, max_length=100, null=True)),
                ('detectee_le', models.DateTimeField(auto_now_add=True)),
                ('resolue_le', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('OPEN', 'Open'), ('INVESTIGATING', 'Investigating'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=50)),
                ('note_resolution', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anomalies_detection',
                'ordering': ['-detectee_le'],
                'indexes': [models.Index(fields=['severite', 'statut'], name='anomalies_d_severit_12ad4a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Chariot',
            fields=[
                ('id_chariot', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code_chariot', models.CharField(max_length=50, unique=True)),
                ('statut', models.CharField(choices=[('AVAILABLE', 'Available'), ('IN_USE', 'In Use'), ('MAINTENANCE', 'Maintenance'), ('INACTIVE', 'Inactive')], default='AVAILABLE', max_length=50)),
                ('capacite', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('id_emplacement_courant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chariots_courants', to='warhouse.emplacement')),
                ('id_entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chariots', to='warhouse.entrepot')),
            ],
            options={
                'db_table': 'chariots',
            },
        ),
        migrations.CreateModel(
            name='ChariotOperation',
            fields=[
                ('id_chariot_operation', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_assignation', models.DateTimeField(auto_now_add=True)),
                ('date_liberation', models.DateTimeField(blank=True, null=True)),
                ('id_chariot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='warhouse.chariot')),
                ('id_emplacement_courant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chariot_operations', to='warhouse.emplacement')),
            ],
            options={
                'db_table': 'chariot_operations',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id_commande', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_commande', models.CharField(choices=[('COMMAND', 'Command Order'), ('PREPARATION', 'Preparation Order'), ('PICKING', 'Picking Order')], max_length=50)),
                ('statut', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATED', 'Generated'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_le', models.DateTimeField(auto_now_add=True)),
                ('debut_le', models.DateTimeField(blank=True, null=True)),
                ('fin_le', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes_creees', to='Users.utilisateur')),
            ],
            options={
                'db_table': 'commandes',
                'ordering': ['-creation_le'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentStockageIA',
            fields=[
                ('id_assignment', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('version_algorithme', models.CharField(max_length=50)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('id_emplacement_assigne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_ia', to='warhouse.emplacement')),
                ('id_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_ia', to='Produit.produit')),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_ia', to='warhouse.commande')),
            ],
            options={
                'db_table': 'assignments_stockage_ia',
            },
        ),
        migrations.CreateModel(
            name='NiveauStockage',
            fields=[
                ('id_niveau', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('code_niveau', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_stockage', to='warhouse.entrepot')),
            ],
            options={
                'db_table': 'niveaux_stockage',
                'unique_together': {('id_entrepot', 'code_niveau')},
            },
        ),
        migrations.AddField(
            model_name='emplacement',
            name='id_niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplacements', to='warhouse.niveaustockage'),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id_operation', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_operation', models.CharField(choices=[('RECEPTION', 'Reception'), ('TRANSFERT', 'Transfer'), ('PICKING', 'Picking'), ('LIVRAISON', 'Delivery')], max_length=50)),
                ('statut', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('execute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='Users.utilisateur')),
                ('id_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='warhouse.commande')),
            ],
            options={
                'db_table': 'operations',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='OperationOffline',
            fields=[
                ('id_operation', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_operation', models.CharField(max_length=100)),
                ('donnees_operation', models.JSONField()),
                ('statut', models.CharField(choices=[('PENDING', 'Pending'), ('SYNCED', 'Synced'), ('FAILED', 'Failed'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=50)),
                ('timestamp_local', models.DateTimeField()),
                ('timestamp_sync', models.DateTimeField(blank=True, null=True)),
                ('erreur_sync', models.TextField(blank=True, null=True)),
                ('tentatives_sync', models.IntegerField(default=0)),
                ('id_utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations_offline', to='Users.utilisateur')),
            ],
            options={
                'db_table': 'operations_offline',
                'ordering': ['-timestamp_local'],
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id_override', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_entite', models.CharField(choices=[('PREPARATION_ORDER', 'Preparation Order Override'), ('PICKING_ORDER', 'Picking Order Override'), ('STORAGE_ASSIGNMENT', 'Storage Assignment Override'), ('ROUTE', 'Route Override')], max_length=50)),
                ('id_entite', models.CharField(max_length=100)),
                ('justification', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('id_commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overrides', to='warhouse.commande')),
                ('override_par', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='Users.utilisateur')),
            ],
            options={
                'db_table': 'overrides',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='PrevisionIA',
            fields=[
                ('id_prevision', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('date_prevision', models.DateField()),
                ('quantite_prevue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confiance_score', models.FloatField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsions_ia', to='Produit.produit')),
            ],
            options={
                'db_table': 'previsions_ia',
                'ordering': ['-date_prevision'],
            },
        ),
        migrations.CreateModel(
            name='ResultatLivraison',
            fields=[
                ('id_resultat', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('statut', models.CharField(choices=[('VALIDATED', 'Validated'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=50)),
                ('date_validation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('id_commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultat_livraison', to='warhouse.commande')),
                ('valide_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livraisons_validees', to='Users.utilisateur')),
            ],
            options={
                'db_table': 'resultats_livraison',
            },
        ),
        migrations.CreateModel(
            name='RoutePickingIA',
            fields=[
                ('id_route', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('donnees_route', models.JSONField()),
                ('distance_totale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temps_estime', models.IntegerField(blank=True, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_picking_ia', to='warhouse.commande')),
            ],
            options={
                'db_table': 'routes_picking_ia',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id_audit', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_action', models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('OVERRIDE', 'Override'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EXPORT', 'Export'), ('IMPORT', 'Import'), ('SYNC', 'Sync')], max_length=50)),
                ('type_entite', models.CharField(max_length=100)),
                ('id_entite', models.CharField(blank=True, max_length=100, null=True)),
                ('ancienne_valeur', models.JSONField(blank=True, null=True)),
                ('nouvelle_valeur', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('adresse_ip', models.CharField(blank=True, max_length=45, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('execute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_audit', to='Users.utilisateur')),
            ],
            options={
                'db_table': 'journal_audit',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['execute_par', 'timestamp'], name='journal_aud_execute_2d6b82_idx'), models.Index(fields=['type_entite', 'timestamp'], name='journal_aud_type_en_41b7a5_idx')],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id_ligne', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantite_completee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('no_ligne', models.IntegerField()),
                ('id_commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='warhouse.commande')),
                ('id_emplacement_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande_destination', to='warhouse.emplacement')),
                ('id_emplacement_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande_source', to='warhouse.emplacement')),
                ('id_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='Produit.produit')),
            ],
            options={
                'db_table': 'lignes_commande',
                'unique_together': {('id_commande', 'no_ligne')},
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id_mouvement', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('type_mouvement', models.CharField(choices=[('RECEPTION', 'Reception'), ('TRANSFERT', 'Transfer'), ('PICKING', 'Picking'), ('LIVRAISON', 'Delivery'), ('AJUSTEMENT', 'Adjustment'), ('PERTE', 'Loss')], max_length=50)),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('motif_code', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_transaction', models.CharField(blank=True, max_length=100, null=True)),
                ('date_execution', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('execute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='Users.utilisateur')),
                ('id_emplacement_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_destination', to='warhouse.emplacement')),
                ('id_emplacement_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock_source', to='warhouse.emplacement')),
                ('id_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='Produit.produit')),
            ],
            options={
                'db_table': 'mouvements_stock',
                'ordering': ['-date_execution'],
                'indexes': [models.Index(fields=['id_produit', 'date_execution'], name='mouvements__id_prod_1d29ab_idx'), models.Index(fields=['type_mouvement', 'date_execution'], name='mouvements__type_mo_a9a3f1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantite_reservee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lot_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('id_emplacement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='warhouse.emplacement')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='Produit.produit')),
            ],
            options={
                'db_table': 'stocks',
                'unique_together': {('id_produit', 'id_emplacement', 'lot_serie')},
            },
        ),
    ]
