# Generated by Django 5.2.3 on 2026-02-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0002_emplacement_cree_le_emplacement_mise_a_jour_le_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chariot',
            name='id_chariot',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
