# Generated by Django 5.2.3 on 2026-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0003_alter_chariot_id_chariot'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveaustockage',
            name='type_niveau',
            field=models.CharField(choices=[('STOCK', 'Stocking Level'), ('PICKING', 'Picking Level')], default='STOCK', max_length=20),
        ),
    ]
