# Generated by Django 5.2.3 on 2026-02-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0004_niveaustockage_type_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveaustockage',
            name='type_niveau',
            field=models.CharField(choices=[('STOCK', 'Stocking Level')], default='STOCK', max_length=20),
        ),
        migrations.CreateModel(
            name='NiveauPicking',
            fields=[
                ('id_niveau_picking', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('code_niveau', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='niveaux_picking', to='warhouse.entrepot')),
            ],
            options={
                'db_table': 'niveaux_picking',
                'unique_together': {('id_entrepot', 'code_niveau')},
            },
        ),
        migrations.AddField(
            model_name='emplacement',
            name='id_niveau_picking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emplacements', to='warhouse.niveaupicking'),
        ),
    ]
