# Generated by Django 5.2.3 on 2026-02-13 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0003_produit_collisage_fardeau_produit_collisage_palette_and_more'),
        ('warhouse', '0005_alter_niveaustockage_type_niveau_niveaupicking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vrack',
            fields=[
                ('id_vrack', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('quantite', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mise_a_jour_le', models.DateTimeField(auto_now=True)),
                ('id_entrepot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vracks', to='warhouse.entrepot')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vracks', to='Produit.produit')),
            ],
            options={
                'db_table': 'vracks',
                'unique_together': {('id_entrepot', 'id_produit')},
            },
        ),
    ]
