# Generated by Django 5.2.3 on 2026-02-13 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0004_alter_produit_table'),
        ('warhouse', '0006_vrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id_rack', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('code_rack', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('id_niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warhouse.niveaustockage')),
            ],
            options={
                'db_table': 'racks',
            },
        ),
        migrations.CreateModel(
            name='RackProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_assignments', to='Produit.produit')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_products', to='warhouse.rack')),
            ],
            options={
                'db_table': 'rack_products',
                'unique_together': {('rack', 'product')},
            },
        ),
    ]
