# Generated by Django 5.2.3 on 2026-02-13 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0007_rack_rackproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='rack',
            name='capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='rack',
            name='id_niveau_picking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warhouse.niveaupicking'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='id_niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warhouse.niveaustockage'),
        ),
        migrations.AlterField(
            model_name='rack',
            name='id_rack',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
