# Generated by Django 5.2.3 on 2026-02-13 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0008_rack_capacity_rack_id_niveau_picking_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='id_niveau_picking',
            new_name='picking_floor',
        ),
        migrations.RemoveField(
            model_name='rack',
            name='id_niveau',
        ),
        migrations.AddField(
            model_name='rack',
            name='storage_floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='racks', to='warhouse.niveaustockage'),
        ),
    ]
