# Generated by Django 5.2.3 on 2026-02-13 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0009_rename_id_niveau_picking_rack_picking_floor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emplacement',
            old_name='id_niveau_picking',
            new_name='picking_floor',
        ),
        migrations.RenameField(
            model_name='emplacement',
            old_name='id_niveau',
            new_name='storage_floor',
        ),
    ]
