# Generated by Django 5.2.3 on 2026-02-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0010_rename_id_niveau_picking_emplacement_picking_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalaudit',
            name='id_entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journaux_audit', to='warhouse.entrepot'),
        ),
        migrations.AddField(
            model_name='mouvementstock',
            name='id_entrepot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='warhouse.entrepot'),
        ),
    ]
