# Generated by Django 5.2.3 on 2026-02-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0011_journalaudit_id_entrepot_mouvementstock_id_entrepot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacement',
            name='code_emplacement',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='emplacement',
            unique_together={('id_entrepot', 'code_emplacement')},
        ),
    ]
