# Generated by Django 5.2.3 on 2026-02-13 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warhouse', '0012_alter_emplacement_code_emplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emplacement',
            name='id_emplacement',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='niveaupicking',
            name='id_niveau_picking',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='niveaustockage',
            name='id_niveau',
            field=models.CharField(blank=True, max_length=100, primary_key=True, serialize=False),
        ),
    ]
