# Generated by Django 5.2.3 on 2026-02-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('nom_produit', models.CharField(max_length=255)),
                ('unite_mesure', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=100)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'produits',
            },
        ),
        migrations.CreateModel(
            name='PolitiqueReapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_securite', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('quantite_min_commande', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('taille_lot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('id_produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politique_reapprovisionnement', to='Produit.produit')),
            ],
            options={
                'db_table': 'politique_reapprovisionnement',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantite_demande', models.DecimalField(decimal_places=2, max_digits=12)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_demandes', to='Produit.produit')),
            ],
            options={
                'db_table': 'historique_demande',
            },
        ),
        migrations.CreateModel(
            name='DelaisApprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_jours', models.IntegerField()),
                ('id_produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delai_approvisionnement', to='Produit.produit')),
            ],
            options={
                'db_table': 'delais_approvisionnement',
            },
        ),
        migrations.CreateModel(
            name='CodeBarresProduit',
            fields=[
                ('code_barres', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type_code_barres', models.CharField(max_length=50)),
                ('principal', models.BooleanField(default=False)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_barres', to='Produit.produit')),
            ],
            options={
                'db_table': 'codes_barres_produits',
            },
        ),
        migrations.CreateModel(
            name='cmd_achat_ouvertes_opt',
            fields=[
                ('id_commande_achat', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('quantite_commandee', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_reception_prevue', models.DateField()),
                ('statut', models.CharField(choices=[('OPEN', 'Open'), ('PARTIALLY_RECEIVED', 'Partially Received'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes_achat', to='Produit.produit')),
            ],
            options={
                'db_table': 'cmd_achat_ouvertes_opt',
            },
        ),
    ]
