# Generated by Django 5.2.3 on 2026-02-13 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_produit',
            field=models.CharField(blank=True, max_length=10, primary_key=True, serialize=False),
        ),
    ]
