# Generated by Django 5.2.3 on 2026-02-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0002_alter_produit_id_produit'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='collisage_fardeau',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='collisage_palette',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='poids',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='produit',
            table='articles',
        ),
    ]
