# Generated by Django 5.2.3 on 2026-02-13 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0003_produit_collisage_fardeau_produit_collisage_palette_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='produit',
            table='produit',
        ),
    ]
