# Generated by Django 5.2.3 on 2026-02-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0004_alter_produit_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='id_rack',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
