# Generated by Django 5.2.3 on 2026-02-13 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0006_produit_id_rack_fk'),
        ('warhouse', '0013_alter_emplacement_id_emplacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='id_rack',
            field=models.ForeignKey(blank=True, db_column='id_rack', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='warhouse.rack'),
        ),
    ]
