# Generated by Django 5.2.3 on 2026-02-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0007_alter_produit_id_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebarresproduit',
            name='code_barre_palette',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
