# Generated by Django 5.2.3 on 2026-02-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0008_codebarresproduit_code_barre_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebarresproduit',
            name='code_barre_fardeau',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
