# Generated by Django 5.2.3 on 2026-02-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0010_alter_produit_collisage_fardeau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='collisage_palette',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
