# Generated by Django 5.2.3 on 2026-02-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produit', '0011_alter_produit_collisage_palette'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='poids',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=10, null=True),
        ),
    ]
