# Generated by Django 5.2.11 on 2026-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100)),
                ('task_type', models.CharField(choices=[('PICKING', 'Picking Optimization'), ('FORECAST', 'Demand Forecasting')], max_length=20)),
                ('predicted_value', models.FloatField()),
                ('actual_value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'ai_performance_logs',
            },
        ),
    ]
