# Generated by Django 5.2.3 on 2026-02-12 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_complet', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('OPERATOR', 'Operator'), ('MANAGER', 'Manager'), ('ADMIN', 'Administrator'), ('VIEWER', 'Viewer')], max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'utilisateurs',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
