# Generated by Django 5.2.3 on 2026-02-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_utilisateur_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
