# Generated by Django 5.2.3 on 2026-02-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_utilisateur_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administrator')], max_length=50),
        ),
    ]
