# Generated by Django 5.2.3 on 2026-02-13 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_utilisateur_adresse_utilisateur_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
