import React, { useState, useEffect } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  FlatList, 
  TouchableOpacity, 
  TextInput, 
  ActivityIndicator,
  Alert,
} from 'react-native';
import { Feather } from '@expo/vector-icons';
import { lightTheme } from '../../../constants/theme.js';
import { apiCall } from '../../../services/api';
import CollapsibleManagementCard from '../../../components/CollapsibleManagementCard';
import ManagementModal from '../../../components/ManagementModal';

const UserManagement = ({ user: currentUser }) => {
  const [users, setUsers] = useState([]);
  const [filteredUsers, setFilteredUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [modalVisible, setModalVisible] = useState(false);
  const [editingUser, setEditingUser] = useState(null);
  
  // Form state
  const [formData, setFormData] = useState({
    id_utilisateur: '',
    nom_complet: '',
    role: 'EMPLOYEE',
    email: '',
    telephone: '',
    adresse: '',
    password: '',
    is_banned: false
  });

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      setLoading(true);
      const data = await apiCall('/users/users/', 'GET');
      setUsers(data);
      setFilteredUsers(data);
    } catch (error) {
      console.error('Error fetching users:', error);
      Alert.alert('Error', 'Failed to load users');
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = (text) => {
    setSearchQuery(text);
    if (!text) {
      setFilteredUsers(users);
      return;
    }
    const filtered = users.filter(user => 
      (user.nom_complet && user.nom_complet.toLowerCase().includes(text.toLowerCase())) ||
      (user.id_utilisateur && user.id_utilisateur.toLowerCase().includes(text.toLowerCase()))
    );
    setFilteredUsers(filtered);
  };

  const handleToggleStatus = (user) => {
    const action = user.is_banned ? 'Unban' : 'Ban';
    Alert.alert(
      `${action} User`,
      `Are you sure you want to ${action.toLowerCase()} this user?`,
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: action, 
          style: user.is_banned ? 'default' : 'destructive',
          onPress: async () => {
            try {
              await apiCall(`/users/users/${user.id_utilisateur}/`, 'PATCH', { is_banned: !user.is_banned });
              fetchUsers();
            } catch (error) {
              Alert.alert('Error', `Failed to ${action.toLowerCase()} user`);
            }
          }
        }
      ]
    );
  };

  const handleDeleteUser = (user) => {
    Alert.alert(
      'Delete User',
      `Are you sure you want to permanently delete ${user.nom_complet}?`,
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: 'Delete', 
          style: 'destructive',
          onPress: async () => {
            try {
              await apiCall(`/users/users/${user.id_utilisateur}/`, 'DELETE');
              Alert.alert('Success', 'User deleted successfully');
              fetchUsers();
            } catch (error) {
              console.error('Delete error:', error);
              Alert.alert('Error', 'Failed to delete user');
            }
          }
        }
      ]
    );
  };

  const openAddModal = () => {
    setEditingUser(null);
    setFormData({
      id_utilisateur: '',
      nom_complet: '',
      role: 'EMPLOYEE',
      email: '',
      telephone: '',
      adresse: '',
      password: '',
      is_banned: false
    });
    setModalVisible(true);
  };

  const openEditModal = (user) => {
    setEditingUser(user);
    setFormData({
      id_utilisateur: user.id_utilisateur,
      nom_complet: user.nom_complet,
      role: user.role,
      email: user.email,
      telephone: user.telephone,
      adresse: user.adresse,
      password: '', // Don't show password
      is_banned: user.is_banned
    });
    setModalVisible(true);
  };

  const handleSave = async () => {
    if (!formData.nom_complet) {
      Alert.alert('Error', 'Full Name is required');
      return;
    }

    try {
      if (editingUser) {
        // Edit existing user
        await apiCall(`/users/users/${editingUser.id_utilisateur}/`, 'PUT', formData);
      } else {
        // Add new user - ID is now auto-generated by backend
        const { id_utilisateur, ...newUserData } = formData;
        await apiCall('/users/users/', 'POST', newUserData);
      }
      setModalVisible(false);
      fetchUsers();
    } catch (error) {
      console.error('Save error:', error);
      Alert.alert('Error', 'Failed to save user info');
    }
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <View style={styles.searchContainer}>
          <Feather name="search" size={20} color="#7D7D7D" style={styles.searchIcon} />
          <TextInput
            style={styles.searchInput}
            placeholder="Rechercher..."
            value={searchQuery}
            onChangeText={handleSearch}
          />
        </View>
        <TouchableOpacity style={styles.addButton} onPress={openAddModal}>
          <Feather name="plus" size={24} color="#fff" />
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.centered}>
          <ActivityIndicator size="large" color="#2196F3" />
        </View>
      ) : (
        <FlatList
          data={filteredUsers}
          keyExtractor={(item) => item.id_utilisateur}
          renderItem={({ item }) => (
            <CollapsibleManagementCard
              title={item.nom_complet || 'Sans nom'}
              subtitle={item.role}
              iconName="user"
              iconColor={item.role === 'ADMIN' ? '#E91E63' : item.role === 'SUPERVISOR' ? '#FF9800' : '#2196F3'}
              status={item.is_banned ? "Banni" : "Actif"}
              statusColor={item.is_banned ? "#F44336" : "#4CAF50"}
              onEdit={() => openEditModal(item)}
              onDelete={() => handleDeleteUser(item)}
              details={[
                { label: 'ID', value: item.id_utilisateur },
                { label: 'Email', value: item.email || 'N/A' },
                { label: 'Tél', value: item.telephone || 'N/A' },
                { label: 'Adresse', value: item.adresse || 'N/A' },
              ]}
              customActions={[
                {
                  icon: item.is_banned ? 'unlock' : 'lock',
                  color: item.is_banned ? '#4CAF50' : '#F44336',
                  onPress: () => handleToggleStatus(item),
                  label: item.is_banned ? 'Débloquer' : 'Bloquer'
                }
              ]}
            />
          )}
          contentContainerStyle={styles.listContent}
          ListEmptyComponent={
            <View style={styles.centered}>
              <Text style={styles.emptyText}>Aucun utilisateur trouvé</Text>
            </View>
          }
        />
      )}

      {/* Add/Edit Modal */}
      <ManagementModal
        visible={modalVisible}
        onClose={() => setModalVisible(false)}
        onSubmit={handleSave}
        title={editingUser ? 'Modifier Utilisateur' : 'Ajouter Utilisateur'}
        submitting={false}
        submitLabel={editingUser ? 'Enregistrer' : 'Ajouter'}
      >
        <View style={styles.formGroup}>
          <Text style={styles.label}>Nom Complet *</Text>
          <View style={styles.inputContainer}>
            <Feather name="user" size={18} color="#94A3B8" style={styles.inputIcon} />
            <TextInput
              style={styles.input}
              placeholder="Jean Dupont"
              value={formData.nom_complet}
              onChangeText={(text) => setFormData({...formData, nom_complet: text})}
              placeholderTextColor="#94A3B8"
            />
          </View>
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.label}>Role</Text>
          <View style={styles.roleButtonsContainer}>
            {['EMPLOYEE', 'SUPERVISOR', 'ADMIN'].map((role) => (
              <TouchableOpacity
                key={role}
                style={[
                  styles.roleOption,
                  formData.role === role && styles.roleOptionSelected
                ]}
                onPress={() => setFormData({...formData, role: role})}
              >
                <Text style={[
                  styles.roleOptionText,
                  formData.role === role && styles.roleOptionTextSelected
                ]}>{role}</Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.label}>Email</Text>
          <View style={styles.inputContainer}>
            <Feather name="mail" size={18} color="#94A3B8" style={styles.inputIcon} />
            <TextInput
              style={styles.input}
              placeholder="jean@example.com"
              keyboardType="email-address"
              value={formData.email}
              onChangeText={(text) => setFormData({...formData, email: text})}
              placeholderTextColor="#94A3B8"
            />
          </View>
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.label}>Télephone</Text>
          <View style={styles.inputContainer}>
            <Feather name="phone" size={18} color="#94A3B8" style={styles.inputIcon} />
            <TextInput
              style={styles.input}
              placeholder="+212 600000000"
              keyboardType="phone-pad"
              value={formData.telephone}
              onChangeText={(text) => setFormData({...formData, telephone: text})}
              placeholderTextColor="#94A3B8"
            />
          </View>
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.label}>Adresse</Text>
          <View style={[styles.inputContainer, { height: 100, alignItems: 'flex-start', paddingTop: 12 }]}>
            <Feather name="map-pin" size={18} color="#94A3B8" style={[styles.inputIcon, { marginTop: 4 }]} />
            <TextInput
              style={[styles.input, { height: 80, textAlignVertical: 'top' }]}
              placeholder="Casablanca, Maroc"
              multiline
              value={formData.adresse}
              onChangeText={(text) => setFormData({...formData, adresse: text})}
              placeholderTextColor="#94A3B8"
            />
          </View>
        </View>

        <View style={styles.formGroup}>
          <Text style={styles.label}>Mot de passe {editingUser && '(Laisser vide pour garder l\'actuel)'}</Text>
          <View style={styles.inputContainer}>
            <Feather name="lock" size={18} color="#94A3B8" style={styles.inputIcon} />
            <TextInput
              style={styles.input}
              placeholder="********"
              secureTextEntry
              value={formData.password}
              onChangeText={(text) => setFormData({...formData, password: text})}
              placeholderTextColor="#94A3B8"
            />
          </View>
        </View>
      </ManagementModal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F8F9FA' },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    backgroundColor: '#FFF',
    borderBottomWidth: 1,
    borderBottomColor: '#F1F5F9',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F1F5F9',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 50,
    marginRight: 12,
  },
  searchIcon: { marginRight: 10 },
  searchInput: { flex: 1, fontSize: 16, color: '#1E293B' },
  addButton: {
    width: 48, height: 48, borderRadius: 14, backgroundColor: '#2196F3',
    justifyContent: 'center', alignItems: 'center',
    elevation: 4, shadowColor: '#2196F3', shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3, shadowRadius: 8
  },
  listContent: { paddingVertical: 12, paddingBottom: 100 },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  emptyText: { color: '#94A3B8', marginTop: 20, fontSize: 16 },
  label: { fontSize: 14, fontWeight: '700', marginBottom: 8, color: '#475569' },
  formGroup: { marginBottom: 20 },
  inputContainer: {
    backgroundColor: '#F8FAFC', borderRadius: 12, paddingHorizontal: 12,
    borderWidth: 1, borderColor: '#E2E8F0', flexDirection: 'row', alignItems: 'center',
    height: 54
  },
  inputIcon: { marginRight: 10 },
  input: { flex: 1, height: 54, fontSize: 16, color: '#1E293B' },
  roleButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8
  },
  roleOption: {
    flex: 1,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFF',
  },
  roleOptionSelected: {
    backgroundColor: '#2196F3',
    borderColor: '#2196F3',
  },
  roleOptionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
  },
  roleOptionTextSelected: {
    color: '#FFF',
  },
});

export default UserManagement;
