import React, { useState, useEffect } from 'react';
import { 
  View, 
  Text, 
  StyleSheet, 
  FlatList, 
  TouchableOpacity, 
  TextInput, 
  ActivityIndicator,
  Alert,
  Modal,
  ScrollView,
} from 'react-native';
import { Feather } from '@expo/vector-icons';
import { lightTheme } from '../../../constants/theme.js';
import { apiCall } from '../../../services/api';
import UserCard from '../../../components/UserCard';

const UserManagement = ({ user: currentUser }) => {
  const [users, setUsers] = useState([]);
  const [filteredUsers, setFilteredUsers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [modalVisible, setModalVisible] = useState(false);
  const [editingUser, setEditingUser] = useState(null);
  
  // Form state
  const [formData, setFormData] = useState({
    id_utilisateur: '',
    nom_complet: '',
    role: 'EMPLOYEE',
    email: '',
    telephone: '',
    adresse: '',
    password: '',
    is_banned: false
  });

  useEffect(() => {
    fetchUsers();
  }, []);

  const fetchUsers = async () => {
    try {
      setLoading(true);
      const data = await apiCall('/users/users/', 'GET');
      setUsers(data);
      setFilteredUsers(data);
    } catch (error) {
      console.error('Error fetching users:', error);
      Alert.alert('Error', 'Failed to load users');
    } finally {
      setLoading(false);
    }
  };

  const handleSearch = (text) => {
    setSearchQuery(text);
    if (!text) {
      setFilteredUsers(users);
      return;
    }
    const filtered = users.filter(user => 
      (user.nom_complet && user.nom_complet.toLowerCase().includes(text.toLowerCase())) ||
      (user.id_utilisateur && user.id_utilisateur.toLowerCase().includes(text.toLowerCase()))
    );
    setFilteredUsers(filtered);
  };

  const handleToggleStatus = (user) => {
    const action = user.is_banned ? 'Unban' : 'Ban';
    Alert.alert(
      `${action} User`,
      `Are you sure you want to ${action.toLowerCase()} this user?`,
      [
        { text: 'Cancel', style: 'cancel' },
        { 
          text: action, 
          style: user.is_banned ? 'default' : 'destructive',
          onPress: async () => {
            try {
              await apiCall(`/users/users/${user.id_utilisateur}/`, 'PUT', { is_banned: !user.is_banned });
              fetchUsers();
            } catch (error) {
              Alert.alert('Error', `Failed to ${action.toLowerCase()} user`);
            }
          }
        }
      ]
    );
  };

  const openAddModal = () => {
    setEditingUser(null);
    setFormData({
      id_utilisateur: '',
      nom_complet: '',
      role: 'EMPLOYEE',
      email: '',
      telephone: '',
      adresse: '',
      password: '',
      is_banned: false
    });
    setModalVisible(true);
  };

  const openEditModal = (user) => {
    setEditingUser(user);
    setFormData({
      id_utilisateur: user.id_utilisateur,
      nom_complet: user.nom_complet,
      role: user.role,
      email: user.email,
      telephone: user.telephone,
      adresse: user.adresse,
      password: '', // Don't show password
      is_banned: user.is_banned
    });
    setModalVisible(true);
  };

  const handleSave = async () => {
    if (!formData.nom_complet) {
      Alert.alert('Error', 'Full Name is required');
      return;
    }

    try {
      if (editingUser) {
        // Edit existing user
        await apiCall(`/users/users/${editingUser.id_utilisateur}/`, 'PUT', formData);
      } else {
        // Add new user - ID is now auto-generated by backend
        const { id_utilisateur, ...newUserData } = formData;
        await apiCall('/users/users/', 'POST', newUserData);
      }
      setModalVisible(false);
      fetchUsers();
    } catch (error) {
      console.error('Save error:', error);
      Alert.alert('Error', 'Failed to save user info');
    }
  };

  return (
    <View style={styles.container}>
      {/* Header with Search and Add Button */}
      <View style={styles.header}>
        <View style={styles.searchContainer}>
          <Feather name="search" size={20} color="#7D7D7D" style={styles.searchIcon} />
          <TextInput
            style={styles.searchInput}
            placeholder="Search Users..."
            value={searchQuery}
            onChangeText={handleSearch}
          />
        </View>
        <TouchableOpacity style={styles.addButton} onPress={openAddModal}>
          <Feather name="plus" size={24} color="#fff" />
        </TouchableOpacity>
      </View>

      {loading ? (
        <View style={styles.centered}>
          <ActivityIndicator size="large" color="#00a3ff" />
        </View>
      ) : (
        <FlatList
          data={filteredUsers}
          keyExtractor={(item) => item.id_utilisateur}
          renderItem={({ item }) => (
            <UserCard 
              user={item} 
              currentUserRole={currentUser?.user_role}
              onToggleStatus={handleToggleStatus} 
              onEdit={openEditModal} 
            />
          )}
          contentContainerStyle={styles.listContent}
          ListEmptyComponent={
            <View style={styles.centered}>
              <Text style={styles.emptyText}>No users found</Text>
            </View>
          }
        />
      )}

      {/* Add/Edit Modal */}
      <Modal
        visible={modalVisible}
        animationType="slide"
        transparent={true}
        onRequestClose={() => setModalVisible(false)}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.modalContent}>
            <View style={styles.modalHeader}>
              <Text style={styles.modalTitle}>{editingUser ? 'Edit User' : 'Add New User'}</Text>
              <TouchableOpacity onPress={() => setModalVisible(false)}>
                <Feather name="x" size={24} color="#333" />
              </TouchableOpacity>
            </View>

            <ScrollView style={styles.modalForm}>
              {editingUser && (
                <>
                  <Text style={styles.inputLabel}>User ID (Fixed)</Text>
                  <TextInput
                    style={[styles.input, styles.disabledInput]}
                    value={formData.id_utilisateur}
                    editable={false}
                  />
                </>
              )}

              <Text style={styles.inputLabel}>Full Name</Text>
              <TextInput
                style={styles.input}
                placeholder="John Doe"
                value={formData.nom_complet}
                onChangeText={(text) => setFormData({...formData, nom_complet: text})}
              />

              <Text style={styles.inputLabel}>Role</Text>
              <View style={styles.roleButtonsContainer}>
                {['EMPLOYEE', 'SUPERVISOR', 'ADMIN'].map((role) => (
                  <TouchableOpacity
                    key={role}
                    style={[
                      styles.roleOption,
                      formData.role === role && styles.roleOptionSelected
                    ]}
                    onPress={() => setFormData({...formData, role: role})}
                  >
                    <Text style={[
                      styles.roleOptionText,
                      formData.role === role && styles.roleOptionTextSelected
                    ]}>{role}</Text>
                  </TouchableOpacity>
                ))}
              </View>

              <Text style={styles.inputLabel}>Email</Text>
              <TextInput
                style={styles.input}
                placeholder="john@example.com"
                keyboardType="email-address"
                value={formData.email}
                onChangeText={(text) => setFormData({...formData, email: text})}
              />

              <Text style={styles.inputLabel}>Phone</Text>
              <TextInput
                style={styles.input}
                placeholder="+123456789"
                keyboardType="phone-pad"
                value={formData.telephone}
                onChangeText={(text) => setFormData({...formData, telephone: text})}
              />

              <Text style={styles.inputLabel}>Address</Text>
              <TextInput
                style={[styles.input, { height: 80 }]}
                placeholder="123 Street, City"
                multiline
                value={formData.adresse}
                onChangeText={(text) => setFormData({...formData, adresse: text})}
              />

              <Text style={styles.inputLabel}>Password {editingUser && '(Leave blank to keep current)'}</Text>
              <TextInput
                style={styles.input}
                placeholder="********"
                secureTextEntry
                value={formData.password}
                onChangeText={(text) => setFormData({...formData, password: text})}
              />

              <TouchableOpacity style={styles.saveButton} onPress={handleSave}>
                <Text style={styles.saveButtonText}>Save User</Text>
              </TouchableOpacity>
              <View style={{ height: 40 }} />
            </ScrollView>
          </View>
        </View>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  searchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 50,
    marginRight: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3.84,
    elevation: 5,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#333',
  },
  addButton: {
    backgroundColor: '#00a3ff',
    width: 50,
    height: 50,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#00a3ff",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  listContent: {
    paddingHorizontal: 12,
    paddingBottom: 20,
    paddingTop: 0,
  },
  centered: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
  },
  emptyText: {
    fontSize: 16,
    color: '#7D7D7D',
  },
  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 25,
    maxHeight: '90%',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#04324C',
  },
  modalForm: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#4A4A4A',
    marginBottom: 8,
    marginTop: 15,
  },
  input: {
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    padding: 15,
    fontSize: 16,
    color: '#333',
    borderWidth: 1,
    borderColor: '#EEE',
  },
  disabledInput: {
    opacity: 0.6,
    backgroundColor: '#EEE',
  },
  roleButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 5,
  },
  roleOption: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#DDD',
    marginHorizontal: 4,
  },
  roleOptionSelected: {
    backgroundColor: '#00a3ff',
    borderColor: '#00a3ff',
  },
  roleOptionText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#7D7D7D',
  },
  roleOptionTextSelected: {
    color: '#fff',
  },
  saveButton: {
    backgroundColor: '#00a3ff',
    borderRadius: 15,
    padding: 18,
    alignItems: 'center',
    marginTop: 30,
    shadowColor: "#00a3ff",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 4.65,
    elevation: 8,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '700',
  },
});

export default UserManagement;
