# Generated by Django 5.2.3 on 2026-02-12 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Produit', '0001_initial'),
        ('Users', '0002_utilisateur_delete_customuser'),
        ('warhouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('RECEIPT', 'Receipt'), ('TRANSFER', 'Transfer'), ('ISSUE', 'Issue'), ('ADJUSTMENT', 'Adjustment')], max_length=50)),
                ('reference_transaction', models.CharField(max_length=100)),
                ('cree_le', models.DateTimeField()),
                ('statut', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cree_par_id_utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='Users.Utilisateur')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='LigneTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ligne', models.IntegerField()),
                ('quantite', models.DecimalField(decimal_places=2, max_digits=12)),
                ('lot_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('code_motif', models.CharField(blank=True, max_length=50, null=True)),
                ('id_emplacement_destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_destination', to='warhouse.emplacement')),
                ('id_emplacement_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_source', to='warhouse.emplacement')),
                ('id_produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_transactions', to='Produit.produit')),
                ('id_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='Transaction.transaction')),
            ],
            options={
                'db_table': 'lignes_transaction',
                'unique_together': {('id_transaction', 'no_ligne')},
            },
        ),
    ]
